fix F17 start date
nsidc/seaice_ecdr pull request #165
Opened 2024-09-26 19:00 UTC by sc0tts

Removes adjustments to v5 code that were used to match CDRv4 fields as closely as possible

2024-09-30 18:47 UTC, sc0tts commented
Work to be done after this PR includes:

1. Use CDRv5 ancillary field information instead of CDRv4
2. Use dynamic tiepoints for Bootstrap calculation

2024-09-30 22:32 UTC, trey-stafford requested changes
Just a few things to review and respond to here! Feel free to resolve and merge while I'm out on vacation this upcoming week.

2024-09-30 22:32 UTC, trey-stafford commented on seaice_ecdr/intermediate_monthly.py
> +    # Note: list comprehension does not work using iterator as key
I think we talked about this in standup for a bit. Based on what you write below, this _should_ work:

```
coord = [daily_cdr_seaice_conc[dim] for dim in dims if dim != "time"]
```

That said, this is clear and easy to read, so no need to change (esp. if there is some issue with  accessing items of `daily_cdr_seaice_conc` with a key in a list comp).

2024-09-30 22:32 UTC, trey-stafford commented on seaice_ecdr/set_daily_ncattrs.py
> +            "valid_range": np.array((0, 200), dtype=np.uint8),
Related to my comment about the max value of 200 in `initial_daily_ecdr.py` - we originally wanted to leave the upper bound of this variable unset. Just want to confirm that we want to change this back to limiting the upper range!

This card has some context: https://trello.com/c/4IfAEWLs/311-ecdr-update-the-rawntseaiceconc-variable-to-allow-values-over-100?search_id=b9792e88-0255-48b0-90de-e04bd0924867

In there, I say:

> The code that set values above 200 to np.nan was actually leftover from an older verison of the nasateam code meant to remove flag values. We no longer include flag values, so this threshold can be removed.

2024-09-30 22:32 UTC, trey-stafford commented on seaice_ecdr/temporal_composite_daily.py
> +        )
Little bit of a nitpick, but I think it's a little more concise to re-write this as a conditional:

```
if temp_comp_2d.shape != (ydim, xdim):
    raise RuntimeError(
        f"Error asserting that squeezed data array is two dimensional with shape ({ydim}, {xdim}); got {temp_comp_2d.shape} instead; Assertion error was {e}"
    )
```

2024-09-30 22:32 UTC, trey-stafford commented on seaice_ecdr/intermediate_monthly.py
> +    # Note: list comprehension does not work using iterator as key
We have gone back and forth on this:

* In db2887cb593336a7d88896909b970ae9193cae87, we replace a valid_range of 0-100 with `valid_min`.
* A few days later, in 91dd602e48c469be02cb39be282c924344c79ec4 I set the `valid_range` to 0-200 and raise an error for values > 200
* Later that day, in 786eea18bc1b2c9570a8f61823df0f7d3df17c87, I remove the `valid_range` and note that a warning is raised for nt > 200, noting that cases > 200 do occur.

2024-09-30 22:33 UTC, trey-stafford commented on seaice_ecdr/set_daily_ncattrs.py
> +            "valid_range": np.array((0, 200), dtype=np.uint8),
We have gone back and forth on this:

* In db2887cb593336a7d88896909b970ae9193cae87, we replace a valid_range of 0-100 with `valid_min`.
* A few days later, in 91dd602e48c469be02cb39be282c924344c79ec4 I set the `valid_range` to 0-200 and raise an error for values > 200
* Later that day, in 786eea18bc1b2c9570a8f61823df0f7d3df17c87, I remove the `valid_range` and note that a warning is raised for nt > 200, noting that cases > 200 do occur.

2024-09-30 22:34 UTC, trey-stafford commented on seaice_ecdr/intermediate_monthly.py
> +        if dim != "time":
This could actually be removed though, as `dims` explicitly excludes `time` above (line 421). 

You could rename the variable to something like `dims_wo_time` to be clear about this and avoid the extra indentation & check here.

2024-10-01 23:46 UTC, sc0tts commented on seaice_ecdr/initial_daily_ecdr.py
> +    bt_coefs["maxic"] = 2.0
The pm_icecon routine requires this value.

The reason for setting a maximum is actually that the resulting value much be able to be represented in packed form -- scale factor 0.01 -- by an unsigned byte that does not have the FillValue of 255.

I set the value here to 2.54 and added comments with the above explanation.

2024-10-01 23:51 UTC, sc0tts commented on seaice_ecdr/initial_daily_ecdr.py
> +    cdr_conc[is_high_siconc] = cdr_conc_max_percent
Good points.  I have eliminated the use of the max_valid_siconc variable.

2024-10-02 00:00 UTC, sc0tts commented on seaice_ecdr/intermediate_monthly.py
> +    # Note: list comprehension does not work using iterator as key
This does work.  I will use this.

2024-10-02 15:48 UTC, sc0tts commented on seaice_ecdr/initial_daily_ecdr.py
> +    max_valid_siconc=200.0,
All references to max_valid_siconc have been removed.

2024-10-02 15:50 UTC, sc0tts commented on seaice_ecdr/temporal_composite_daily.py
> +        )
Agree.  Done.

2024-10-02 15:52 UTC, sc0tts commented on seaice_ecdr/intermediate_monthly.py
> +        if dim != "time":
dims and coords renamed to dims_without_time and coords_without_time respectively.

2024-10-03 15:57 UTC, merged