Add complete daily ecdr
nsidc/seaice_ecdr pull request #24
Opened 2023-10-31 21:45 UTC by sc0tts

Still a few items remaining, eg making sure pass1, pass2 subdirs are properly passed throughout the complete_daily processing stream.

Also need to implement eCDR-specific file name templates.

And some of the QA fields may not be getting properly set yet.

But this will yield initial complete daily fields so that further work -- eg start of monthly composite files -- and comparisons with cdrv4 files can begin

2023-10-31 22:09 UTC, trey-stafford requested changes
Great start! Just a few comments to address.

2023-10-31 22:09 UTC, trey-stafford commented on seaice_ecdr/complete_daily_ecdr.py
> +    array[:] = fill_value
These last two lines could be reduced to one:

```
array = np.full(array_shape, fill_value)
```

https://numpy.org/doc/stable/reference/generated/numpy.full.html

2023-10-31 22:09 UTC, trey-stafford commented on seaice_ecdr/complete_daily_ecdr.py
> +    default=INITIAL_DAILY_OUTPUT_DIR,
Create seprate dir for complete daily files

2023-10-31 22:09 UTC, trey-stafford commented on seaice_ecdr/complete_daily_ecdr.py
> +if __name__ == "__main__":
clean this up before merge

2023-11-01 01:29 UTC, sc0tts commented on seaice_ecdr/complete_daily_ecdr.py
> +    default=INITIAL_DAILY_OUTPUT_DIR,
I added ide_dir, tie_dir, and output_dir in most function calls that need or pass-through dir names

2023-11-01 01:31 UTC, sc0tts commented on seaice_ecdr/complete_daily_ecdr.py
> +if __name__ == "__main__":
By "clean up", do you mean remove the code that calls the make_cdecdr_netcdf() routine if the file is executed?

2023-11-01 01:33 UTC, sc0tts commented on seaice_ecdr/complete_daily_ecdr.py
> +# TODO: Perhaps this isn't needed?  The necessary precursor files can
Removed.  This date iterator is not needed with the recursive code we're using.

2023-11-01 17:35 UTC, trey-stafford commented on seaice_ecdr/complete_daily_ecdr.py
> +if __name__ == "__main__":
Yes, I cleaned this up and added the complete CLI to the standard entrypoint. E.g., this is now possible:

```
$ ./scripts/cli.sh  cdecdr --date 2022-03-02 --hemisphere north --resolution 12
```

2023-11-01 17:51 UTC, merged