Fix missing x y attrs sh
nsidc/seaice_ecdr pull request #70
Opened 2024-01-10 21:00 UTC by trey-stafford

2024-01-10 22:12 UTC, sc0tts commented on scripts/ancillary/fix-sh-xy-attrs.py
> +        valid_range=(ancillary_ds.x.min(), ancillary_ds.x.max()),
I think this valid range assignment isn't quite right.
There's a difference between the "valid_range" and the "actual_range".  

The latter refers to the values in the arrays -- i.e., what would be returned by .min() and .max() functions.

The valid_range should include the entire domain of the grid, and so should go from "x.min() - half-the-grid-cell-width" to "x.max() + half-the-grid-cell-width"

2024-01-10 22:13 UTC, sc0tts commented on scripts/ancillary/fix-sh-xy-attrs.py
> +        valid_range=(ancillary_ds.y.min(), ancillary_ds.y.max()),
As above, valid_range != actual_range

2024-01-10 22:15 UTC, sc0tts requested changes
At some point, we probably need to have a single-source-of-truth for the geospatial netCDF variables/coordinates/dimensions.  

For now, I've been using the appropriate fields in NSIDC-0771 for the polar-stereo grids.

2024-01-10 22:24 UTC, trey-stafford commented on scripts/ancillary/fix-sh-xy-attrs.py
> +        valid_range=(ancillary_ds.x.min(), ancillary_ds.x.max()),
Good catch!

2024-01-11 00:00 UTC, trey-stafford commented on scripts/ancillary/fix-sh-xy-attrs.py
> +        valid_range=(ancillary_ds.x.min(), ancillary_ds.x.max()),
38c2115

2024-01-16 21:16 UTC, merged